# -*- coding: utf-8 -*-
"""AOL 2_Deep Learning_2702749802.ipynb

Automatically generated by Colab.

AOL 2 DEEP LEARNING
CALLISTA SERENA EKAPUTRI - 2702749802
"""

pip install Sastrawi

pip install nlpaug

import re
import nltk
import torch
import torch.nn as nn
import pandas as pd
import numpy as np
import tensorflow as tf
import seaborn as sns
import matplotlib.pyplot as plt

nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('averaged_perceptron_tagger')
nltk.download('averaged_perceptron_tagger_eng')

from nltk.stem import WordNetLemmatizer
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

from sklearn.model_selection import train_test_split, ParameterGrid
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix

from imblearn.over_sampling import SMOTE
from torch.utils.data import Dataset, DataLoader
from transformers import AutoTokenizer, AutoModel

import nlpaug.augmenter.word as naw

all_results = []

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print("Device:", device)

df = pd.read_csv("re_dataset.csv", encoding = "cp1252")
x = df["Tweet"]
y = df["HS"]

print("="*50)
print("Dataset Awal")
print("="*50)

print(df.head())
print("\nShape: ", df.shape)
print("\nKolom: ", df.columns.tolist())
print("\nDistribusi Label HS: ")
print(df["HS"].value_counts())
print("\nMissing Value: ")
print(df.isnull().sum())

x_train, x_test, y_train, y_test = train_test_split(
    x
    , y
    , test_size = 0.2
    , stratify = y
    , random_state = 42
)

print("="*50)
print("Distribusi Data Setelah Splitting")
print("="*50)

print("Train Size: ", x_train.shape)
print("Test Size: ", x_test.shape)
print("\nDistribusi y_train: ")
print(y_train.value_counts())
print("\nDistribusi y_test: ")
print(y_test.value_counts())

factory = StemmerFactory()
stemmer = factory.create_stemmer()

def clean_text(text):
  text = str(text).lower()
  text = re.sub(r'@\w+|#\w+', ' ', text)
  text = re.sub(r'[^\w\s]', ' ', text)
  text = re.sub(r'\d+', ' ', text)
  text = re.sub(r'\s+', ' ', text).strip()
  text = stemmer.stem(text)

  return text

x_train = x_train.apply(clean_text)
x_test = x_test.apply(clean_text)

print("="*50)
print("Data Setelah Preprocessing")
print("="*50)

print(x_train.iloc[:10].values)

train_lengths = x_train.apply(lambda x: len(x.split()))
print("\nRata - rata jumlah kata: ", round(train_lengths.mean(), 2))
print("Minimum kata: ", train_lengths.min())
print("Maximum kata: ", train_lengths.max())

def augment_text(df, samples, pr = 0.2):
    aug = naw.SynonymAug(aug_src = 'wordnet', lang = 'ind')

    new_text = []

    df_n = df[df["HS"] == 0].reset_index(drop = True)

    for i in np.random.randint(0,len(df_n),samples):
        text = df_n.iloc[i]['Tweet']
        augmented_text = aug.augment(text)
        new_text.append(augmented_text)

    new = pd.DataFrame({'Tweet':new_text, 'HS':1})
    df = pd.concat([df, new], axis = 0).reset_index(drop = True)
    return df

# Calculate max_size using y_train
max_size = y_train.value_counts().max() - y_train.value_counts().min()

# Create a DataFrame by combining x_train and y_train
train_df = pd.DataFrame({'Tweet': x_train, 'HS': y_train})

# Call augment_text with the combined DataFrame
train = augment_text(train_df, max_size)

#Since the oversampled data has brackets, we need to remove it first
def remove_brackets(df):
    new_df = df.copy()
    new_df['Tweet'] = new_df['Tweet'].apply(lambda x: " ".join(str(y) for y in x) if isinstance(x, list) else x)
    return new_df
train = remove_brackets(train)

train.info()

train['HS'].value_counts()

models = {
    "IndoBERTweet": "indolem/indobertweet-base-uncased"
}

max_len = 128

class TextDataset(Dataset):
  def __init__(self, input_ids, masks, labels):
    self.input_ids = input_ids
    self.masks = masks
    self.labels = labels

  def __len__(self):
    return len(self.labels)

  def __getitem__(self, idx):
    return {
        "input_ids": torch.tensor(
            self.input_ids[idx]
            , dtype = torch.long
        )
        , "attention_mask": torch.tensor(
            self.masks[idx]
            , dtype = torch.long
        )
        , "labels": torch.tensor(
            self.labels[idx]
            , dtype = torch.float
        )
    }

class indobert_bigru(nn.Module):
  def __init__(self
               , model_name
               , hidden_dim = 128
               , dropout = 0.3):
    super().__init__()
    self.bert = AutoModel.from_pretrained(
        model_name
    )
    bert_dim = self.bert.config.hidden_size

    self.bigru = nn.GRU(
        bert_dim
        , hidden_dim
        , batch_first = True
        , bidirectional = True
    )

    self.dropout = nn.Dropout(dropout)

    self.fc = nn.Linear(
        hidden_dim*2
        , 1
    )

  def forward(self, input_ids, attention_mask):
    output = self.bert(
        input_ids = input_ids
        , attention_mask = attention_mask
    )

    seq = output.last_hidden_state
    gru_out, _ = self.bigru(seq)
    final = gru_out[:, -1, :]
    x = self.dropout(final)
    x = self.fc(x)
    return torch.sigmoid(x)

def evaluate_model(name, y_true, y_pred):
  acc = accuracy_score(y_true, y_pred)
  precision = precision_score(y_true, y_pred)
  recall = recall_score(y_true, y_pred)
  f1 = f1_score(y_true, y_pred)

  print("="*50)
  print(name)
  print("="*50)

  print("Accuracy: ", acc)
  print("Precision: ", precision)
  print("Recall: ", recall)
  print("F1-Score: ", f1)

  print(classification_report(y_true, y_pred))

  cm = confusion_matrix(y_true, y_pred)

  plt.figure(figsize = (5, 4))
  sns.heatmap(
      cm
      , annot = True
      , fmt = "d"
      , cmap = "Blues"
      , xticklabels=["Non-HS (0)", "HS (1)"]
      , yticklabels=["Non-HS (0)", "HS (1)"]
  )
  plt.title(name)
  plt.show()

  return {
      "model_name": name,
      "accuracy": acc,
      "precision": precision,
      "recall": recall,
      "f1_score": f1,
      "y_true": y_true,
      "y_pred": y_pred
  }

param_grid = {
    "hidden_dim": [128]
    , "dropout": [0.5]
    , "lr": [3e-5]
    , "batch_size": [64, 128]
    , "epochs": [10, 20]
}

for model_name, model_path in models.items():

  print("\nRunning: ", model_name)
  tokenizer = AutoTokenizer.from_pretrained(model_path)

  # Use the augmented 'train' DataFrame for x_train and y_train
  x_train_augmented = train['Tweet']
  y_train_augmented = train['HS']

  train_enc = tokenizer(
      list(x_train_augmented) # <--- Changed x_train to x_train_augmented
      , padding = "max_length"
      , truncation = True
      , max_length = max_len
  )

  test_enc = tokenizer(
      list(x_test)
      , padding = "max_length"
      , truncation = True
      , max_length = max_len
  )

  x_train_ids = np.array(train_enc["input_ids"])
  x_train_mask = np.array(train_enc["attention_mask"])
  x_test_ids = np.array(test_enc["input_ids"])
  x_test_mask = np.array(test_enc["attention_mask"])

  print("Tokenized Shape: ", x_train_ids.shape)
  print(pd.Series(y_train_augmented).value_counts())

  best_model = None
  best_param = None
  best_acc = 0
  best_epoch_f1_scores = []
  best_epoch_train_losses = []

  for param in ParameterGrid(param_grid):
    print("Testing: ", param)

    train_dataset = TextDataset(
        x_train_ids
        , x_train_mask
        , y_train_augmented.values
    )

    train_loader = DataLoader(
        train_dataset
        , batch_size = param["batch_size"]
        , shuffle = True
    )

    model = indobert_bigru(
            model_path
            , hidden_dim = param["hidden_dim"]
            , dropout = param["dropout"]
    ).to(device)

    criterion = nn.BCELoss()

    optimizer = torch.optim.Adam(
          model.parameters()
          , lr = param["lr"]
        )

    current_epoch_f1_scores = []
    current_epoch_train_losses = []

    for epoch in range(param["epochs"]):

            print(f"Epoch {epoch+1} started")
            model.train()
            total_train_loss = 0

            for batch in train_loader:

                ids = batch["input_ids"].to(device)
                mask = batch["attention_mask"].to(device)
                labels = batch["labels"].to(device)

                optimizer.zero_grad()

                outputs = model(
                    ids
                    , mask
                ).squeeze()

                loss = criterion(
                    outputs
                    , labels
                )

                loss.backward()
                optimizer.step()
                total_train_loss += loss.item()

            avg_train_loss = total_train_loss / len(train_loader)
            current_epoch_train_losses.append(avg_train_loss)

            model.eval()

            preds = []

            with torch.no_grad():

              for i in range(len(x_test_ids)):

                  ids = torch.tensor(x_test_ids[i:i+1]).to(device)

                  mask = torch.tensor(x_test_mask[i:i+1]).to(device)

                  out = model(
                      ids
                      , mask
                  )

                  pred = 1 if out.item() > 0.5 else 0
                  preds.append(pred)

            score = f1_score(y_test, preds)
            current_epoch_f1_scores.append(score)

            if score > best_acc:
                best_acc = score
                best_model = model
                best_param = param
                best_epoch_f1_scores = list(current_epoch_f1_scores)
                best_epoch_train_losses = list(current_epoch_train_losses)

  print("Best Parameter:", best_param)

  # Plotting the training curve for the best model
  if best_param:
      epochs_range = range(1, len(best_epoch_f1_scores) + 1)

      plt.figure(figsize = (12, 5))

      plt.subplot(1, 2, 1)
      plt.plot(epochs_range, best_epoch_f1_scores, marker = 'o')
      plt.title(f'F1-Score per Epoch for Best {model_name} Model')
      plt.xlabel('Epoch')
      plt.ylabel('F1-Score')
      plt.grid(True)

      plt.subplot(1, 2, 2)
      plt.plot(epochs_range, best_epoch_train_losses, marker = 'o', color = 'red')
      plt.title(f'Training Loss per Epoch for Best {model_name} Model')
      plt.xlabel('Epoch')
      plt.ylabel('Loss')
      plt.grid(True)

      plt.tight_layout()
      plt.show()

best_model.eval()

final_preds = []

with torch.no_grad():

  for i in range(len(x_test_ids)):

      ids = torch.tensor(x_test_ids[i:i+1]).to(device)

      mask = torch.tensor( x_test_mask[i:i+1]).to(device)

      out = best_model(
          ids
          , mask
          )

      pred = 1 if out.item() > 0.5 else 0
      final_preds.append(pred)

result = evaluate_model(
        model_name
        , y_test
        , final_preds
    )

all_results.append(result)

from sklearn.feature_extraction.text import TfidfVectorizer
import scipy.sparse

tfidf_vectorizer = TfidfVectorizer(
    max_features = 5000, # Limit vocabulary size
    ngram_range = (1, 2) # Consider unigrams and bigrams
)

x_train_tfidf = tfidf_vectorizer.fit_transform(x_train)
x_test_tfidf = tfidf_vectorizer.transform(x_test)

print("Original x_train_tfidf shape:", x_train_tfidf.shape)
print("Original y_train value counts:\n", y_train.value_counts())

x_train_augmented = train['Tweet']
y_train_augmented = train['HS']


x_train_tfidf_res = tfidf_vectorizer.transform(x_train_augmented)
y_train_res_tfidf = y_train_augmented

print("\nAfter synonym replacement x_train_tfidf_res shape: ", x_train_tfidf_res.shape)
print("\nAfter synonym replacement y_train_res_tfidf value counts: ", y_train_res_tfidf.value_counts())

class TFIDFGRUClassifier(nn.Module):
  def __init__(self, input_dim, hidden_dim, dropout=0.5, output_dim=1):
    super().__init__()
    self.input_dim = input_dim
    self.hidden_dim = hidden_dim

    # Project TF-IDF features to a dense embedding suitable for GRU
    self.embedding_layer = nn.Linear(input_dim, hidden_dim)

    # Bi-directional GRU layer
    self.gru = nn.GRU(
        hidden_dim
        , hidden_dim
        , batch_first = True
        , bidirectional = True
    )

    self.dropout = nn.Dropout(dropout)

    self.fc = nn.Linear(hidden_dim * 2, output_dim)

  def forward(self, x):
    embedded = self.embedding_layer(x)
    embedded = embedded.unsqueeze(1) # Shape: (batch_size, 1, hidden_dim)
    gru_out, _ = self.gru(embedded)
    final = gru_out[:, -1, :]
    x = self.dropout(final)
    x = self.fc(x)
    return torch.sigmoid(x)

class TFIDFIterableDataset(Dataset):
  def __init__(self, features, labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self, idx):
    feature_tensor = torch.tensor(
        self.features[idx].toarray().flatten()
        , dtype=torch.float
    )
    return {
        "features": feature_tensor,
        "labels": torch.tensor(self.labels[idx], dtype=torch.float)
    }

param_grid_tfidf = {
    "hidden_dim": [128]
    , "dropout": [0.5]
    , "lr": [3e-5]
    , "batch_size": [64, 128]
    , "epochs": [10, 20]
}

TFIDF_model_name = "TF-IDF BiGRU"


print("\nRunning:", TFIDF_model_name)

train_dataset_tfidf = TFIDFIterableDataset(
    x_train_tfidf_res,
    y_train_res_tfidf.values
)

test_dataset_tfidf = TFIDFIterableDataset(
    x_test_tfidf,
    y_test.values
)


best_tfidf_model = None
best_tfidf_param = None
best_tfidf_acc = 0
best_epoch_f1_scores_tfidf = []
best_epoch_train_losses_tfidf = []

for param in ParameterGrid(param_grid_tfidf):
    print("Testing:", param)

    train_loader_tfidf = DataLoader(
        train_dataset_tfidf
        , batch_size = param["batch_size"]
        , shuffle = True
    )

    model_tfidf = TFIDFGRUClassifier(
        input_dim=x_train_tfidf_res.shape[1]
        , hidden_dim = param["hidden_dim"]
        , dropout = param["dropout"]
    ).to(device)

    criterion_tfidf = nn.BCELoss()
    optimizer_tfidf = torch.optim.Adam(
        model_tfidf.parameters()
        , lr = param["lr"]
    )

    current_epoch_f1_scores_tfidf = []
    current_epoch_train_losses_tfidf = []

    for epoch in range(param["epochs"]):
        model_tfidf.train()
        total_train_loss_tfidf = 0

        for batch in train_loader_tfidf:
            features = batch["features"].to(device)
            labels = batch["labels"].to(device)

            optimizer_tfidf.zero_grad()

            outputs = model_tfidf(features).squeeze()

            loss_tfidf = criterion_tfidf(
                outputs
                , labels
            )

            loss_tfidf.backward()
            optimizer_tfidf.step()
            total_train_loss_tfidf += loss_tfidf.item()

        avg_train_loss_tfidf = total_train_loss_tfidf / len(train_loader_tfidf)
        current_epoch_train_losses_tfidf.append(avg_train_loss_tfidf)

        model_tfidf.eval()
        preds_tfidf = []

        with torch.no_grad():
            test_loader_tfidf = DataLoader(
                test_dataset_tfidf
                , batch_size=param["batch_size"]
                , shuffle = False
            )
            for batch in test_loader_tfidf:
                features = batch["features"].to(device)
                out = model_tfidf(features).squeeze()
                preds_batch = (out > 0.5).int().tolist()
                preds_tfidf.extend(preds_batch)

        score_tfidf = f1_score(y_test, preds_tfidf)
        current_epoch_f1_scores_tfidf.append(score_tfidf)

        if score_tfidf > best_tfidf_acc:
            best_tfidf_acc = score_tfidf
            best_tfidf_model = model_tfidf
            best_tfidf_param = param
            best_epoch_f1_scores_tfidf = list(current_epoch_f1_scores_tfidf)
            best_epoch_train_losses_tfidf = list(current_epoch_train_losses_tfidf)

print("Best Parameter for TF-IDF Bi-GRU:", best_tfidf_param)

# Plotting the training curve for the best TF-IDF model
if best_tfidf_param:
    epochs_range_tfidf = range(1, len(best_epoch_f1_scores_tfidf) + 1)

    plt.figure(figsize = (12, 5))

    plt.subplot(1, 2, 1)
    plt.plot(epochs_range_tfidf, best_epoch_f1_scores_tfidf, marker = 'o')
    plt.title(f'F1-Score per Epoch for Best {TFIDF_model_name}')
    plt.xlabel('Epoch')
    plt.ylabel('F1-Score')
    plt.grid(True)

    plt.subplot(1, 2, 2)
    plt.plot(epochs_range_tfidf, best_epoch_train_losses_tfidf, marker = 'o', color = 'red')
    plt.title(f'Training Loss per Epoch for Best {TFIDF_model_name}')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.grid(True)

    plt.tight_layout()
    plt.show()

# Final evaluation for the best TF-IDF model
best_tfidf_model.eval()
final_preds_tfidf = []

with torch.no_grad():
    test_loader_tfidf = DataLoader(
        test_dataset_tfidf
        , batch_size=best_tfidf_param["batch_size"]
        , shuffle = False
    )
    for batch in test_loader_tfidf:
        features = batch["features"].to(device)
        out = best_tfidf_model(features).squeeze()
        preds_batch = (out > 0.5).int().tolist()
        final_preds_tfidf.extend(preds_batch)

result_tfidf = evaluate_model(
    TFIDF_model_name
    , y_test
    , final_preds_tfidf
)

all_results.append(result_tfidf)

result_df = pd.DataFrame(
    all_results,
    columns=[
        "model_name"
        , "accuracy"
        , "precision"
        , "recall"
        , "f1_score"
    ]
).rename(columns={
    "model_name": "Model"
    , "accuracy": "Accuracy"
    , "precision": "Precision"
    , "recall": "Recall"
    , "f1_score": "F1-Score"
})

result_df = result_df.sort_values(
    by = "Accuracy"
    , ascending = False
)
print("="*50)
print("FINAL RESULT")
print("="*50)
print(result_df)

# ===============================================================
# VISUALIZATION
# ===============================================================

plt.figure(figsize = (10,6))
sns.barplot(
    data = result_df
    , x = "Accuracy"
    , y = "Model"
)

plt.title("Comparison Models")
plt.show()

for item in all_results:

    model_name = item["model_name"]
    y_true = item["y_true"]
    y_pred = item["y_pred"]

    cm = confusion_matrix(y_true, y_pred)

    print("=" * 50)
    print("Model :", model_name)
    print("Confusion Matrix")
    print(cm)

    plt.figure(figsize=(6,5))
    sns.heatmap(
        cm
        , annot = True
        , fmt = "d"
        , cmap = "Blues"
        , xticklabels = ["Non-HS (0)", "HS (1)"]
        , yticklabels = ["Non-HS (0)", "HS (1)"]
    )

    plt.title(f"Confusion Matrix - {model_name}")
    plt.xlabel("Predicted Label")
    plt.ylabel("True Label")
    plt.show()

